### ISSUE TITLE
Context menu appears far away from where the mouse is

### ISSUE THREAD

**Issue by sgalkina** [DD-DeCaF/metabolica-ui-map#104]
![Screen Shot 2017-10-20 at 16.36.58.png](https://images.zenhubusercontent.com/59ddfe76b0222d5de47b3425/7285fe6f-5d3a-457c-8b3d-09751ea4560c)

**Comment by matyasfodor** [comment]
Caused by the fix for non-overlapping sidenav. The toolbar and the left sidebar cause the offset.
