### ISSUE TITLE
A white area in the bottom appeared after the hovering over search menu was fixed

### ISSUE THREAD

**Issue by sgalkina** [DD-DeCaF/metabolica-ui-map#105]
![Screen Shot 2017-10-20 at 16.39.04.png](https://images.zenhubusercontent.com/59ddfe76b0222d5de47b3425/ca6e205b-53f7-487e-801b-8186169b917d)

**Comment by matyasfodor** [comment]
How to reproduce it? What's the screen size? I could not reproduce it neither with my 13'' MacBook, nor with my external screen.
