### ISSUE TITLE
Remove "lodash" dependency

### ISSUE THREAD

**Issue by lyschoening** [DD-DeCaF/metabolica-ui-map#11]
Not super-high priority, but at least in our internal projects we have guidelines to avoid lodash and underscore. Nowadays plain TS/JS has similar functionality and there is no point in learning one more library when it doesn't actually add much value.

**Comment by warlink** [comment]
Some of the functionality being used from lodash is not in TS or JS and would be too much work to redo.

**Comment by lyschoening** [comment]
Is it possible to keep the issue open then? It does not have to be done now, but it's essentially legacy code that will need to be fixed at some point.
