### ISSUE TITLE
Eliminate redundant calls when maps are loaded

### ISSUE THREAD

**Issue by phantomas1234** [DD-DeCaF/metabolica-ui-map#129]
![image.png](https://images.zenhubusercontent.com/59dc9349b0222d5de47b04bd/33bc130a-bbee-4f6a-9f14-57b0b6511a66)

**Comment by matyasfodor** [comment]
This will be solved if we switch to observables. Also I found that we're loading the map 5 times because different watchers fire subsequently, so that's why loading the map + the model is so slow.

**Comment by phantomas1234** [comment]
That sounds great. There is an issue for observables on the board already, right?
