### ISSUE TITLE
Search for reactions and metabolites across multiple maps

### ISSUE THREAD

**Issue by Midnighter** [DD-DeCaF/metabolica-ui-map#47]
If I don't know beforehand on which map to find a reaction or metabolite of interest, it'd be great to have a search functionality that tells me on which maps I need to look.

**Comment by matyasfodor** [comment]
Why is this closed? Is there another card instead of this?

**Comment by sgalkina** [comment]
yes closed because of the epic https://app.zenhub.com/workspace/o/dd-decaf/scrum/issues/215
