### ISSUE TITLE
The menu for switching maps uses <md-button>, should be wrapped in <md-menu-item>

### ISSUE THREAD

**Issue by lyschoening** [DD-DeCaF/metabolica-ui-map#5]
The buttons in the menu are upper case and have a padding because the wrong elements where used.

**Comment by lyschoening** [comment]
~I also suggest placing the menu to the left of the button rather than on top of it.~

Strike that. It's in the spec.

Could we align it so that the active map is always under the button at first click? I believe md-menu-origin can help with that.

**Comment by warlink** [comment]
Not sure why you would want that?
1) The user wouldn't want to select the already selected map
2) if the last map is selected that would push the menu out the top of the page

**Comment by lyschoening** [comment]
1. It's in the material design specs and it's generally how the interface works. There are multiple reasons. a) in this case specifically, you have to click the button to see what map you have open. b) people often click buttons for no reason and if they want to leave the menu they should not have to move the mouse out of the menu to be able to cancel the action. If the current option is under the mouse they can just click again.

2. No, the menu would at most be pushed to the top of the page and angular material would make the menu scrollable and scroll it to the right position. It's a non-issue.
