### ISSUE TITLE
Enhancements to pathway map UI (by Lars)

### ISSUE THREAD

**Issue by lyschoening** [DD-DeCaF/metabolica-ui-map#6]
Some issues and suggestions for updating the map info sidenav:

- Placement on the right might be better
- Should have a drop shadow, at least dp-1
- The genotype changes should be shown as `<genotype>`
- The tab header should stay fixed when the list is scrolled
- The scroll bar goes under the list on macOS
- Consider using either a <md-list> or md-table (https://github.com/daniel-nagy/md-data-table) for consistency

**Comment by lyschoening** [comment]
Why was this closed?

**Comment by phantomas1234** [comment]
Need to split those into individual cards.

**Comment by warlink** [comment]
Made individual issues
