### ISSUE TITLE
Module breaks authentication in whole app

### ISSUE THREAD

**Issue by lyschoening** [DD-DeCaF/metabolica-ui-map#61]
The module turns off the authentication required flag. This means users never get notified that they are logged out and to them it just looks like the system is down.

https://github.com/DD-DeCaF/metabolica-ui-map/blob/master/src/pathwayvis/pathwayvis.module.js#L46

**Comment by sgalkina** [comment]
fixed by https://github.com/DD-DeCaF/metabolica-ui-map/commit/22f0d0ce1e21e0193f118eb57c570fbcc660add6#diff-53f8af26b8ad9873efea1777be1140bc
