### ISSUE TITLE
Pathway map steals "0" and "1" keys

### ISSUE THREAD

**Issue by lyschoening** [DD-DeCaF/metabolica-ui-map#95]
This breaks the search function while on the pathway map page

**Comment by phantomas1234** [comment]
I can reproduce this (in the search field). Also, the backspace key seems to be broken. Unfortunately this behavior is kept if one move to one of the other applications. I'd guess that it is escher's keyboard shortcuts that somehow interfere here.

**Comment by matyasfodor** [comment]
Escher map swallows hotkeys
